name: Backend
on: [push]
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get dependencies
      working-directory: backend
      run: |
        go get -v -t -d ./...
        go get -v github.com/golang/mock/mockgen@1.3.1

    - name: Build
      working-directory: backend
      run: go build -v ./...

    - name: Generate
      working-directory: backend
      run: |
        export PATH=$PATH:~/go/bin
        go generate -v ./...
      continue-on-error: true

    - name: Generate2
      working-directory: backend
      run: |
        export PATH=$PATH:~/go/bin
        go generate -v ./...      

    - name: Unit Test
      working-directory: backend
      run: go test -v -test.short ./...

    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions@0.1.1
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GC_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GC_SERVICE_ACCOUNT_KEY }}

    - name: Deploy to AppEngine
      working-directory: backend
      run: |
        gcloud config set project ${{ secrets.GC_PROJECT_ID }}
        gcloud components install app-engine-go
        gcloud app deploy
